version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    user: root
    ports:
      - 8866:8080
      - 50000:50000
    privileged: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/local/bin/docker:/bin/docker
      - jenkins-home:/var/jenkins_home

volumes:
  jenkins-home:
